<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Remove_add_blue_border_8</name>
   <tag></tag>
   <elementGuidId>edcd14c5-6b17-4312-9b75-1961d1611b83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bottom-slider-id']/div[9]/figure/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_blue_border</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.reevio.com/templates//global(3039)/slideImage/cad66849360b5207b9ecb8e790de64391561381760844.jpeg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bottom-slider-id&quot;)/div[@class=&quot;swiper-slide slide-item image-container selected&quot;]/figure[@class=&quot;slide-img ui-sortable-handle&quot;]/div[@class=&quot;hold-asp-ratio&quot;]/div[@class=&quot;asp-content a-hover&quot;]/img[@class=&quot;add_blue_border&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bottom-slider-id']/div[9]/figure/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.reevio.com/templates//global(3039)/slideImage/cad66849360b5207b9ecb8e790de64391561381760844.jpeg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/figure/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
